import is from "../../mod.ts";
import { assertEquals } from "https://deno.land/std@0.224.0/assert/assert_equals.ts";

Deno.test("alphabetic", () => {
  assertEquals(is.alphabetic("a"), true);
  assertEquals(is.alphabetic("A"), true);
  assertEquals(is.alphabetic("f"), true);
  assertEquals(is.alphabetic("F"), true);
  assertEquals(is.alphabetic("g"), true);
  assertEquals(is.alphabetic("G"), true);
  assertEquals(is.alphabetic("z"), true);
  assertEquals(is.alphabetic("Z"), true);

  assertEquals(is.alphabetic(""), false);
  assertEquals(is.alphabetic(" "), false);
  assertEquals(is.alphabetic("0"), false);
  assertEquals(is.alphabetic("1"), false);
  assertEquals(is.alphabetic("9"), false);
  assertEquals(is.alphabetic("!"), false);
  assertEquals(is.alphabetic("@"), false);
  assertEquals(is.alphabetic("#"), false);
  assertEquals(is.alphabetic("$"), false);
  assertEquals(is.alphabetic("%"), false);
  assertEquals(is.alphabetic("^"), false);
  assertEquals(is.alphabetic("&"), false);
  assertEquals(is.alphabetic("*"), false);
  assertEquals(is.alphabetic("("), false);
  assertEquals(is.alphabetic(")"), false);
  assertEquals(is.alphabetic("-"), false);
  assertEquals(is.alphabetic("_"), false);
  assertEquals(is.alphabetic("+"), false);
  assertEquals(is.alphabetic("="), false);
  assertEquals(is.alphabetic("{"), false);
  assertEquals(is.alphabetic("["), false);
  assertEquals(is.alphabetic("}"), false);
  assertEquals(is.alphabetic("]"), false);
  assertEquals(is.alphabetic("|"), false);
  assertEquals(is.alphabetic("\\"), false);
  assertEquals(is.alphabetic(":"), false);
  assertEquals(is.alphabetic(";"), false);
  assertEquals(is.alphabetic('"'), false);
  assertEquals(is.alphabetic("'"), false);
  assertEquals(is.alphabetic("<"), false);
  assertEquals(is.alphabetic(","), false);
  assertEquals(is.alphabetic(">"), false);
  assertEquals(is.alphabetic("."), false);
  assertEquals(is.alphabetic("?"), false);
  assertEquals(is.alphabetic("/"), false);
  assertEquals(is.alphabetic("`"), false);
  assertEquals(is.alphabetic("~"), false);
});
