import is from "../../mod.ts";
import { assertEquals } from "https://deno.land/std@0.224.0/assert/assert_equals.ts";

Deno.test("ascii", () => {
  assertEquals(is.ascii(""), true);
  assertEquals(is.ascii(" "), true);
  assertEquals(is.ascii("a"), true);
  assertEquals(is.ascii("A"), true);
  assertEquals(is.ascii("0"), true);
  assertEquals(is.ascii("1"), true);
  assertEquals(is.ascii("9"), true);
  assertEquals(is.ascii("f"), true);
  assertEquals(is.ascii("F"), true);
  assertEquals(is.ascii("g"), true);
  assertEquals(is.ascii("G"), true);
  assertEquals(is.ascii("z"), true);
  assertEquals(is.ascii("Z"), true);
  assertEquals(is.ascii("!"), true);
  assertEquals(is.ascii("@"), true);
  assertEquals(is.ascii("#"), true);
  assertEquals(is.ascii("$"), true);
  assertEquals(is.ascii("%"), true);
  assertEquals(is.ascii("^"), true);
  assertEquals(is.ascii("&"), true);
  assertEquals(is.ascii("*"), true);
  assertEquals(is.ascii("("), true);
  assertEquals(is.ascii(")"), true);
  assertEquals(is.ascii("-"), true);
  assertEquals(is.ascii("_"), true);
  assertEquals(is.ascii("+"), true);
  assertEquals(is.ascii("="), true);
  assertEquals(is.ascii("{"), true);
  assertEquals(is.ascii("["), true);
  assertEquals(is.ascii("}"), true);
  assertEquals(is.ascii("]"), true);
  assertEquals(is.ascii("|"), true);
  assertEquals(is.ascii("\\"), true);
  assertEquals(is.ascii(":"), true);
  assertEquals(is.ascii(";"), true);
  assertEquals(is.ascii('"'), true);
  assertEquals(is.ascii("'"), true);
  assertEquals(is.ascii("<"), true);
  assertEquals(is.ascii(","), true);
  assertEquals(is.ascii(">"), true);
  assertEquals(is.ascii("."), true);
  assertEquals(is.ascii("?"), true);
  assertEquals(is.ascii("/"), true);
  assertEquals(is.ascii("`"), true);
  assertEquals(is.ascii("~"), true);
});
